package com.ccsp.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AdminPlanExclusion generated by hbm2java
 */
@Entity
@Table(name = "AdminPlanExclusion", schema = "dbo", catalog = "ccsp",
    uniqueConstraints = @UniqueConstraint(columnNames = "AdminPlanId"))
public class AdminPlanExclusion implements java.io.Serializable {


  private byte[] nodeId;
  private Short nodeLevel;
  private int adminPlanId;
  private int benefitServiceRuleId;
  private int planRuleId;
  private int corporateBenefitServiceId;
  private int stateBenefitServiceId;
  private int grandfatheredBenefitServiceId;
  private int networkBenefitServiceId;

  public AdminPlanExclusion() {}


  public AdminPlanExclusion(byte[] nodeId, int adminPlanId, int benefitServiceRuleId,
      int planRuleId, int corporateBenefitServiceId, int stateBenefitServiceId,
      int grandfatheredBenefitServiceId, int networkBenefitServiceId) {
    this.nodeId = nodeId;
    this.adminPlanId = adminPlanId;
    this.benefitServiceRuleId = benefitServiceRuleId;
    this.planRuleId = planRuleId;
    this.corporateBenefitServiceId = corporateBenefitServiceId;
    this.stateBenefitServiceId = stateBenefitServiceId;
    this.grandfatheredBenefitServiceId = grandfatheredBenefitServiceId;
    this.networkBenefitServiceId = networkBenefitServiceId;
  }

  public AdminPlanExclusion(byte[] nodeId, Short nodeLevel, int adminPlanId,
      int benefitServiceRuleId, int planRuleId, int corporateBenefitServiceId,
      int stateBenefitServiceId, int grandfatheredBenefitServiceId, int networkBenefitServiceId) {
    this.nodeId = nodeId;
    this.nodeLevel = nodeLevel;
    this.adminPlanId = adminPlanId;
    this.benefitServiceRuleId = benefitServiceRuleId;
    this.planRuleId = planRuleId;
    this.corporateBenefitServiceId = corporateBenefitServiceId;
    this.stateBenefitServiceId = stateBenefitServiceId;
    this.grandfatheredBenefitServiceId = grandfatheredBenefitServiceId;
    this.networkBenefitServiceId = networkBenefitServiceId;
  }

  @Id


  @Column(name = "NodeId", unique = true, nullable = false)
  public byte[] getNodeId() {
    return this.nodeId;
  }

  public void setNodeId(byte[] nodeId) {
    this.nodeId = nodeId;
  }


  @Column(name = "NodeLevel")
  public Short getNodeLevel() {
    return this.nodeLevel;
  }

  public void setNodeLevel(Short nodeLevel) {
    this.nodeLevel = nodeLevel;
  }


  @Column(name = "AdminPlanId", unique = true, nullable = false)
  public int getAdminPlanId() {
    return this.adminPlanId;
  }

  public void setAdminPlanId(int adminPlanId) {
    this.adminPlanId = adminPlanId;
  }


  @Column(name = "BenefitServiceRuleId", nullable = false)
  public int getBenefitServiceRuleId() {
    return this.benefitServiceRuleId;
  }

  public void setBenefitServiceRuleId(int benefitServiceRuleId) {
    this.benefitServiceRuleId = benefitServiceRuleId;
  }


  @Column(name = "PlanRuleId", nullable = false)
  public int getPlanRuleId() {
    return this.planRuleId;
  }

  public void setPlanRuleId(int planRuleId) {
    this.planRuleId = planRuleId;
  }


  @Column(name = "CorporateBenefitServiceID", nullable = false)
  public int getCorporateBenefitServiceId() {
    return this.corporateBenefitServiceId;
  }

  public void setCorporateBenefitServiceId(int corporateBenefitServiceId) {
    this.corporateBenefitServiceId = corporateBenefitServiceId;
  }


  @Column(name = "StateBenefitServiceID", nullable = false)
  public int getStateBenefitServiceId() {
    return this.stateBenefitServiceId;
  }

  public void setStateBenefitServiceId(int stateBenefitServiceId) {
    this.stateBenefitServiceId = stateBenefitServiceId;
  }


  @Column(name = "GrandfatheredBenefitServiceID", nullable = false)
  public int getGrandfatheredBenefitServiceId() {
    return this.grandfatheredBenefitServiceId;
  }

  public void setGrandfatheredBenefitServiceId(int grandfatheredBenefitServiceId) {
    this.grandfatheredBenefitServiceId = grandfatheredBenefitServiceId;
  }


  @Column(name = "NetworkBenefitServiceID", nullable = false)
  public int getNetworkBenefitServiceId() {
    return this.networkBenefitServiceId;
  }

  public void setNetworkBenefitServiceId(int networkBenefitServiceId) {
    this.networkBenefitServiceId = networkBenefitServiceId;
  }



}


