package com.ccsp.entity;



import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AdminBenefitSvcCostShareOverrides generated by hbm2java
 */
@Entity
@Table(name = "AdminBenefitSvcCostShareOverrides",
    uniqueConstraints = @UniqueConstraint(columnNames = "AdminPlanId"))
public class AdminBenefitSvcCostShareOverrides implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -5804729642049856825L;
private int id;
  private int adminPlanId;
  private Integer benefitServiceId;
  private Integer pharmacyCategoryId;
  private int grandfatheredBenefitServiceId;
  private int stateBenefitServiceId;
  private int networkBenefitServiceId;
  private int costShareId;
  private int costShareValueInt;
  private BigDecimal costShareValueDecimal;
  private String costShareValueVarchar;
  private Date overrideStartDate;
  private Date overrideEndDate;

  public AdminBenefitSvcCostShareOverrides() {}


  public AdminBenefitSvcCostShareOverrides(int id, int adminPlanId,
      int grandfatheredBenefitServiceId, int stateBenefitServiceId, int networkBenefitServiceId,
      int costShareId, int costShareValueInt, BigDecimal costShareValueDecimal,
      String costShareValueVarchar, Date overrideStartDate) {
    this.id = id;
    this.adminPlanId = adminPlanId;
    this.grandfatheredBenefitServiceId = grandfatheredBenefitServiceId;
    this.stateBenefitServiceId = stateBenefitServiceId;
    this.networkBenefitServiceId = networkBenefitServiceId;
    this.costShareId = costShareId;
    this.costShareValueInt = costShareValueInt;
    this.costShareValueDecimal = costShareValueDecimal;
    this.costShareValueVarchar = costShareValueVarchar;
    this.overrideStartDate = overrideStartDate;
  }

  public AdminBenefitSvcCostShareOverrides(int id, int adminPlanId, Integer benefitServiceId,
      Integer pharmacyCategoryId, int grandfatheredBenefitServiceId, int stateBenefitServiceId,
      int networkBenefitServiceId, int costShareId, int costShareValueInt,
      BigDecimal costShareValueDecimal, String costShareValueVarchar, Date overrideStartDate,
      Date overrideEndDate) {
    this.id = id;
    this.adminPlanId = adminPlanId;
    this.benefitServiceId = benefitServiceId;
    this.pharmacyCategoryId = pharmacyCategoryId;
    this.grandfatheredBenefitServiceId = grandfatheredBenefitServiceId;
    this.stateBenefitServiceId = stateBenefitServiceId;
    this.networkBenefitServiceId = networkBenefitServiceId;
    this.costShareId = costShareId;
    this.costShareValueInt = costShareValueInt;
    this.costShareValueDecimal = costShareValueDecimal;
    this.costShareValueVarchar = costShareValueVarchar;
    this.overrideStartDate = overrideStartDate;
    this.overrideEndDate = overrideEndDate;
  }

  @Id


  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }


  @Column(name = "AdminPlanId", unique = true, nullable = false)
  public int getAdminPlanId() {
    return this.adminPlanId;
  }

  public void setAdminPlanId(int adminPlanId) {
    this.adminPlanId = adminPlanId;
  }


  @Column(name = "BenefitServiceID")
  public Integer getBenefitServiceId() {
    return this.benefitServiceId;
  }

  public void setBenefitServiceId(Integer benefitServiceId) {
    this.benefitServiceId = benefitServiceId;
  }


  @Column(name = "PharmacyCategoryID")
  public Integer getPharmacyCategoryId() {
    return this.pharmacyCategoryId;
  }

  public void setPharmacyCategoryId(Integer pharmacyCategoryId) {
    this.pharmacyCategoryId = pharmacyCategoryId;
  }


  @Column(name = "GrandfatheredBenefitServiceID", nullable = false)
  public int getGrandfatheredBenefitServiceId() {
    return this.grandfatheredBenefitServiceId;
  }

  public void setGrandfatheredBenefitServiceId(int grandfatheredBenefitServiceId) {
    this.grandfatheredBenefitServiceId = grandfatheredBenefitServiceId;
  }


  @Column(name = "StateBenefitServiceID", nullable = false)
  public int getStateBenefitServiceId() {
    return this.stateBenefitServiceId;
  }

  public void setStateBenefitServiceId(int stateBenefitServiceId) {
    this.stateBenefitServiceId = stateBenefitServiceId;
  }


  @Column(name = "NetworkBenefitServiceID", nullable = false)
  public int getNetworkBenefitServiceId() {
    return this.networkBenefitServiceId;
  }

  public void setNetworkBenefitServiceId(int networkBenefitServiceId) {
    this.networkBenefitServiceId = networkBenefitServiceId;
  }


  @Column(name = "CostShareId", nullable = false)
  public int getCostShareId() {
    return this.costShareId;
  }

  public void setCostShareId(int costShareId) {
    this.costShareId = costShareId;
  }


  @Column(name = "CostShareValueInt", nullable = false)
  public int getCostShareValueInt() {
    return this.costShareValueInt;
  }

  public void setCostShareValueInt(int costShareValueInt) {
    this.costShareValueInt = costShareValueInt;
  }


  @Column(name = "CostShareValueDecimal", nullable = false, precision = 15)
  public BigDecimal getCostShareValueDecimal() {
    return this.costShareValueDecimal;
  }

  public void setCostShareValueDecimal(BigDecimal costShareValueDecimal) {
    this.costShareValueDecimal = costShareValueDecimal;
  }


  @Column(name = "CostShareValueVarchar", nullable = false)
  public String getCostShareValueVarchar() {
    return this.costShareValueVarchar;
  }

  public void setCostShareValueVarchar(String costShareValueVarchar) {
    this.costShareValueVarchar = costShareValueVarchar;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "OverrideStartDate", nullable = false)
  public Date getOverrideStartDate() {
    return this.overrideStartDate;
  }

  public void setOverrideStartDate(Date overrideStartDate) {
    this.overrideStartDate = overrideStartDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "OverrideEndDate")
  public Date getOverrideEndDate() {
    return this.overrideEndDate;
  }

  public void setOverrideEndDate(Date overrideEndDate) {
    this.overrideEndDate = overrideEndDate;
  }



}


