package com.ccsp.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BenefitServiceList generated by hbm2java
 */
@Entity
@Table(name = "BenefitServiceList", schema = "dbo", catalog = "ccsp")
public class BenefitServiceList implements java.io.Serializable {


  private int benefitServiceId;
  private int corporateBenefitServiceId;
  private String benefitServiceCode;
  private String benefitServiceName;
  private String benefitServiceDescription;

  public BenefitServiceList() {}

  public BenefitServiceList(int benefitServiceId, int corporateBenefitServiceId,
      String benefitServiceCode, String benefitServiceName, String benefitServiceDescription) {
    this.benefitServiceId = benefitServiceId;
    this.corporateBenefitServiceId = corporateBenefitServiceId;
    this.benefitServiceCode = benefitServiceCode;
    this.benefitServiceName = benefitServiceName;
    this.benefitServiceDescription = benefitServiceDescription;
  }

  @Id


  @Column(name = "BenefitServiceID", unique = true, nullable = false)
  public int getBenefitServiceId() {
    return this.benefitServiceId;
  }

  public void setBenefitServiceId(int benefitServiceId) {
    this.benefitServiceId = benefitServiceId;
  }


  @Column(name = "CorporateBenefitServiceID", nullable = false)
  public int getCorporateBenefitServiceId() {
    return this.corporateBenefitServiceId;
  }

  public void setCorporateBenefitServiceId(int corporateBenefitServiceId) {
    this.corporateBenefitServiceId = corporateBenefitServiceId;
  }


  @Column(name = "BenefitServiceCode", nullable = false)
  public String getBenefitServiceCode() {
    return this.benefitServiceCode;
  }

  public void setBenefitServiceCode(String benefitServiceCode) {
    this.benefitServiceCode = benefitServiceCode;
  }


  @Column(name = "BenefitServiceName", nullable = false)
  public String getBenefitServiceName() {
    return this.benefitServiceName;
  }

  public void setBenefitServiceName(String benefitServiceName) {
    this.benefitServiceName = benefitServiceName;
  }


  @Column(name = "BenefitServiceDescription", nullable = false)
  public String getBenefitServiceDescription() {
    return this.benefitServiceDescription;
  }

  public void setBenefitServiceDescription(String benefitServiceDescription) {
    this.benefitServiceDescription = benefitServiceDescription;
  }



}


