package com.ccsp.entity;
// default package
// Generated 14 Mar, 2017 8:23:39 PM by Hibernate Tools 5.0.2.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diagnostics generated by hbm2java
 */
@Entity
@Table(name = "diagnostics")
public class Diagnostics implements java.io.Serializable {


  private int id;
  private String name;

  public Diagnostics() {}


  public Diagnostics(int id) {
    this.id = id;
  }

  public Diagnostics(int id, String name) {
    this.id = id;
    this.name = name;
  
  }

  @Id


  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }


  @Column(name = "name", length = 100)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }







}


