package com.ccsp.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NetworkBenefitServiceList generated by hbm2java
 */
@Entity
@Table(name = "NetworkBenefitServiceList", schema = "dbo", catalog = "ccsp")
public class NetworkBenefitServiceList implements java.io.Serializable {


  private int networkBenefitServiceId;
  private int corporateBenefitServiceId;
  private int productTypeId;
  private String networkBenefitServiceCode;
  private String networkBenefitServiceName;
  private String networkBenefitServiceDescription;

  public NetworkBenefitServiceList() {}

  public NetworkBenefitServiceList(int networkBenefitServiceId, int corporateBenefitServiceId,
      int productTypeId, String networkBenefitServiceCode, String networkBenefitServiceName,
      String networkBenefitServiceDescription) {
    this.networkBenefitServiceId = networkBenefitServiceId;
    this.corporateBenefitServiceId = corporateBenefitServiceId;
    this.productTypeId = productTypeId;
    this.networkBenefitServiceCode = networkBenefitServiceCode;
    this.networkBenefitServiceName = networkBenefitServiceName;
    this.networkBenefitServiceDescription = networkBenefitServiceDescription;
  }

  @Id


  @Column(name = "NetworkBenefitServiceID", unique = true, nullable = false)
  public int getNetworkBenefitServiceId() {
    return this.networkBenefitServiceId;
  }

  public void setNetworkBenefitServiceId(int networkBenefitServiceId) {
    this.networkBenefitServiceId = networkBenefitServiceId;
  }


  @Column(name = "CorporateBenefitServiceID", nullable = false)
  public int getCorporateBenefitServiceId() {
    return this.corporateBenefitServiceId;
  }

  public void setCorporateBenefitServiceId(int corporateBenefitServiceId) {
    this.corporateBenefitServiceId = corporateBenefitServiceId;
  }


  @Column(name = "ProductTypeId", nullable = false)
  public int getProductTypeId() {
    return this.productTypeId;
  }

  public void setProductTypeId(int productTypeId) {
    this.productTypeId = productTypeId;
  }


  @Column(name = "NetworkBenefitServiceCode", nullable = false)
  public String getNetworkBenefitServiceCode() {
    return this.networkBenefitServiceCode;
  }

  public void setNetworkBenefitServiceCode(String networkBenefitServiceCode) {
    this.networkBenefitServiceCode = networkBenefitServiceCode;
  }


  @Column(name = "NetworkBenefitServiceName", nullable = false)
  public String getNetworkBenefitServiceName() {
    return this.networkBenefitServiceName;
  }

  public void setNetworkBenefitServiceName(String networkBenefitServiceName) {
    this.networkBenefitServiceName = networkBenefitServiceName;
  }


  @Column(name = "NetworkBenefitServiceDescription", nullable = false)
  public String getNetworkBenefitServiceDescription() {
    return this.networkBenefitServiceDescription;
  }

  public void setNetworkBenefitServiceDescription(String networkBenefitServiceDescription) {
    this.networkBenefitServiceDescription = networkBenefitServiceDescription;
  }



}


