package com.ccsp.entity;

// default package
// Generated 14 Mar, 2017 4:14:47 PM by Hibernate Tools 5.0.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Plans generated by hbm2java
 */
@Entity
@Table(name = "plans",
    uniqueConstraints = @UniqueConstraint(columnNames = "planid"))
public class Plans implements java.io.Serializable {


  private long id;
  private String planid;
  private String planName;

  public Plans() {}


  public Plans(long id, String planid) {
    this.id = id;
    this.planid = planid;
  }

  public Plans(long id, String planid, String planName) {
    this.id = id;
    this.planid = planid;
    this.planName = planName;
  }

  @Id


  @Column(name = "id", unique = true, nullable = false)
  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }


  @Column(name = "planid", unique = true, nullable = false, length = 50)
  public String getPlanid() {
    return this.planid;
  }

  public void setPlanid(String planid) {
    this.planid = planid;
  }


  @Column(name = "plan_name", length = 50)
  public String getPlanName() {
    return this.planName;
  }

  public void setPlanName(String planName) {
    this.planName = planName;
  }



}


