package com.ccsp.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProcCodeDiagCodeList generated by hbm2java
 */
@Entity
@Table(name = "ProcCodeDiagCodeList")
public class ProcCodeDiagCodeList implements java.io.Serializable {


  private int id;
  private String procedureCode;
  private String diagonisticCode;
  private int benefitServiceId;
  private int pharmacyCategoryId;
  private int stateBenefitServiceId;
  private int grandfatheredServiceId;
  private int networkBenefitServiceId;

  public ProcCodeDiagCodeList() {}

  public ProcCodeDiagCodeList(int id, String procedureCode, String diagonisticCode,
      int benefitServiceId, int pharmacyCategoryId, int stateBenefitServiceId,
      int grandfatheredServiceId, int networkBenefitServiceId) {
    this.id = id;
    this.procedureCode = procedureCode;
    this.diagonisticCode = diagonisticCode;
    this.benefitServiceId = benefitServiceId;
    this.pharmacyCategoryId = pharmacyCategoryId;
    this.stateBenefitServiceId = stateBenefitServiceId;
    this.grandfatheredServiceId = grandfatheredServiceId;
    this.networkBenefitServiceId = networkBenefitServiceId;
  }

  @Id


  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }


  @Column(name = "ProcedureCode", nullable = false)
  public String getProcedureCode() {
    return this.procedureCode;
  }

  public void setProcedureCode(String procedureCode) {
    this.procedureCode = procedureCode;
  }


  @Column(name = "DiagonisticCode", nullable = false)
  public String getDiagonisticCode() {
    return this.diagonisticCode;
  }

  public void setDiagonisticCode(String diagonisticCode) {
    this.diagonisticCode = diagonisticCode;
  }


  @Column(name = "BenefitServiceID", nullable = false)
  public int getBenefitServiceId() {
    return this.benefitServiceId;
  }

  public void setBenefitServiceId(int benefitServiceId) {
    this.benefitServiceId = benefitServiceId;
  }


  @Column(name = "PharmacyCategoryID", nullable = false)
  public int getPharmacyCategoryId() {
    return this.pharmacyCategoryId;
  }

  public void setPharmacyCategoryId(int pharmacyCategoryId) {
    this.pharmacyCategoryId = pharmacyCategoryId;
  }


  @Column(name = "StateBenefitServiceID", nullable = false)
  public int getStateBenefitServiceId() {
    return this.stateBenefitServiceId;
  }

  public void setStateBenefitServiceId(int stateBenefitServiceId) {
    this.stateBenefitServiceId = stateBenefitServiceId;
  }


  @Column(name = "GrandfatheredServiceID", nullable = false)
  public int getGrandfatheredServiceId() {
    return this.grandfatheredServiceId;
  }

  public void setGrandfatheredServiceId(int grandfatheredServiceId) {
    this.grandfatheredServiceId = grandfatheredServiceId;
  }


  @Column(name = "NetworkBenefitServiceID", nullable = false)
  public int getNetworkBenefitServiceId() {
    return this.networkBenefitServiceId;
  }

  public void setNetworkBenefitServiceId(int networkBenefitServiceId) {
    this.networkBenefitServiceId = networkBenefitServiceId;
  }



}


