package com.ccsp.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductTypeList generated by hbm2java
 */
@Entity
@Table(name = "ProductTypeList", schema = "dbo", catalog = "ccsp")
public class ProductTypeList implements java.io.Serializable {


  private int productTypeId;
  private String productTypeName;
  private String productTypeDescription;

  public ProductTypeList() {}

  public ProductTypeList(int productTypeId, String productTypeName, String productTypeDescription) {
    this.productTypeId = productTypeId;
    this.productTypeName = productTypeName;
    this.productTypeDescription = productTypeDescription;
  }

  @Id


  @Column(name = "ProductTypeId", unique = true, nullable = false)
  public int getProductTypeId() {
    return this.productTypeId;
  }

  public void setProductTypeId(int productTypeId) {
    this.productTypeId = productTypeId;
  }


  @Column(name = "ProductTypeName", nullable = false)
  public String getProductTypeName() {
    return this.productTypeName;
  }

  public void setProductTypeName(String productTypeName) {
    this.productTypeName = productTypeName;
  }


  @Column(name = "ProductTypeDescription", nullable = false)
  public String getProductTypeDescription() {
    return this.productTypeDescription;
  }

  public void setProductTypeDescription(String productTypeDescription) {
    this.productTypeDescription = productTypeDescription;
  }



}


