package com.ccsp.entity;



import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AdministrativePlanCostShareOverrides generated by hbm2java
 */
@Entity
@Table(name = "AdministrativePlanCostShareOverrides",
    uniqueConstraints = @UniqueConstraint(columnNames = "AdminPlanId"))
public class AdministrativePlanCostShareOverrides implements java.io.Serializable {


  private int id;
  private int adminPlanId;
  private int costShareId;
  private int costShareValueInt;
  private BigDecimal costShareValueDecimal;
  private String costShareValueVarchar;
  private Date overrideStartDate;
  private Date overrideEndDate;

  public AdministrativePlanCostShareOverrides() {}


  public AdministrativePlanCostShareOverrides(int id, int adminPlanId, int costShareId,
      int costShareValueInt, BigDecimal costShareValueDecimal, String costShareValueVarchar,
      Date overrideStartDate) {
    this.id = id;
    this.adminPlanId = adminPlanId;
    this.costShareId = costShareId;
    this.costShareValueInt = costShareValueInt;
    this.costShareValueDecimal = costShareValueDecimal;
    this.costShareValueVarchar = costShareValueVarchar;
    this.overrideStartDate = overrideStartDate;
  }

  public AdministrativePlanCostShareOverrides(int id, int adminPlanId, int costShareId,
      int costShareValueInt, BigDecimal costShareValueDecimal, String costShareValueVarchar,
      Date overrideStartDate, Date overrideEndDate) {
    this.id = id;
    this.adminPlanId = adminPlanId;
    this.costShareId = costShareId;
    this.costShareValueInt = costShareValueInt;
    this.costShareValueDecimal = costShareValueDecimal;
    this.costShareValueVarchar = costShareValueVarchar;
    this.overrideStartDate = overrideStartDate;
    this.overrideEndDate = overrideEndDate;
  }

  @Id


  @Column(name = "id", unique = true, nullable = false)
  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }


  @Column(name = "AdminPlanId", unique = true, nullable = false)
  public int getAdminPlanId() {
    return this.adminPlanId;
  }

  public void setAdminPlanId(int adminPlanId) {
    this.adminPlanId = adminPlanId;
  }


  @Column(name = "CostShareId", nullable = false)
  public int getCostShareId() {
    return this.costShareId;
  }

  public void setCostShareId(int costShareId) {
    this.costShareId = costShareId;
  }


  @Column(name = "CostShareValueInt", nullable = false)
  public int getCostShareValueInt() {
    return this.costShareValueInt;
  }

  public void setCostShareValueInt(int costShareValueInt) {
    this.costShareValueInt = costShareValueInt;
  }


  @Column(name = "CostShareValueDecimal", nullable = false, precision = 15)
  public BigDecimal getCostShareValueDecimal() {
    return this.costShareValueDecimal;
  }

  public void setCostShareValueDecimal(BigDecimal costShareValueDecimal) {
    this.costShareValueDecimal = costShareValueDecimal;
  }


  @Column(name = "CostShareValueVarchar", nullable = false)
  public String getCostShareValueVarchar() {
    return this.costShareValueVarchar;
  }

  public void setCostShareValueVarchar(String costShareValueVarchar) {
    this.costShareValueVarchar = costShareValueVarchar;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "OverrideStartDate", nullable = false)
  public Date getOverrideStartDate() {
    return this.overrideStartDate;
  }

  public void setOverrideStartDate(Date overrideStartDate) {
    this.overrideStartDate = overrideStartDate;
  }


  @Column(name = "OverrideEndDate")
  public Date getOverrideEndDate() {
    return this.overrideEndDate;
  }

  public void setOverrideEndDate(Date overrideEndDate) {
    this.overrideEndDate = overrideEndDate;
  }



}


