package com.ccsp.entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * MemberAccumulatorData generated by hbm2java
 */
@Entity
@Table(name = "MemberAccumulatorData")
public class MemberAccumulatorData implements java.io.Serializable {

	@Id
	@Column(name = "NodeId", columnDefinition = "BINARY(254)", length = 254, unique = true, nullable = false)
	private byte[] nodeId;
	private int claimId;
	private int memberId;
	private int benefitServiceId;
	private long indeductible;
	private long oondeductible;
	private long inopx;
	private long oonopx;

	public MemberAccumulatorData() {
	}

	public MemberAccumulatorData(byte[] nodeId, int claimId, int memberId, int benefitServiceId, long indeductible,
			long oondeductible, long inopx, long oonopx) {
		this.nodeId = nodeId;
		this.claimId = claimId;
		this.memberId = memberId;
		this.benefitServiceId = benefitServiceId;
		this.indeductible = indeductible;
		this.oondeductible = oondeductible;
		this.inopx = inopx;
		this.oonopx = oonopx;
	}

	public byte[] getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(byte[] nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "ClaimId", nullable = false)
	public int getClaimId() {
		return this.claimId;
	}

	public void setClaimId(int claimId) {
		this.claimId = claimId;
	}

	@Column(name = "MemberId", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "BenefitServiceID", nullable = false)
	public int getBenefitServiceId() {
		return this.benefitServiceId;
	}

	public void setBenefitServiceId(int benefitServiceId) {
		this.benefitServiceId = benefitServiceId;
	}

	@Column(name = "INDeductible", nullable = false, precision = 18, scale = 0)
	public long getIndeductible() {
		return this.indeductible;
	}

	public void setIndeductible(long indeductible) {
		this.indeductible = indeductible;
	}

	@Column(name = "OONDeductible", nullable = false, precision = 18, scale = 0)
	public long getOondeductible() {
		return this.oondeductible;
	}

	public void setOondeductible(long oondeductible) {
		this.oondeductible = oondeductible;
	}

	@Column(name = "INOPX", nullable = false, precision = 18, scale = 0)
	public long getInopx() {
		return this.inopx;
	}

	public void setInopx(long inopx) {
		this.inopx = inopx;
	}

	@Column(name = "OONOPX", nullable = false, precision = 18, scale = 0)
	public long getOonopx() {
		return this.oonopx;
	}

	public void setOonopx(long oonopx) {
		this.oonopx = oonopx;
	}

}
