package com.ccsp.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetallicList generated by hbm2java
 */
@Entity
@Table(name = "MetallicList")
public class MetallicList implements java.io.Serializable {


  private int metallicId;
  private String metallicName;
  private String metallicDescription;

  public MetallicList() {}

  public MetallicList(int metallicId, String metallicName, String metallicDescription) {
    this.metallicId = metallicId;
    this.metallicName = metallicName;
    this.metallicDescription = metallicDescription;
  }

  @Id


  @Column(name = "MetallicId", unique = true, nullable = false)
  public int getMetallicId() {
    return this.metallicId;
  }

  public void setMetallicId(int metallicId) {
    this.metallicId = metallicId;
  }


  @Column(name = "MetallicName", nullable = false)
  public String getMetallicName() {
    return this.metallicName;
  }

  public void setMetallicName(String metallicName) {
    this.metallicName = metallicName;
  }


  @Column(name = "MetallicDescription", nullable = false)
  public String getMetallicDescription() {
    return this.metallicDescription;
  }

  public void setMetallicDescription(String metallicDescription) {
    this.metallicDescription = metallicDescription;
  }



}


